export const items = {
  short_sword: {
    itemId: 'short_sword',
    name: 'Short Sword',
    image: 'short-sword',
    type: 'mainHand',
    level: 1,
    damage: [3, 5],
    power: 3,
    probability: 10,
    sellPrice: 50,
    buyPrice: 120,
    height: 3,
    width: 1,
  },
  planks: {
    itemId: 'planks',
    name: 'Planks',
    image: 'planks',
    type: 'offHand',
    level: 1,
    armor: 10,
    power: 3,
    probability: 15,
    sellPrice: 30,
    buyPrice: 75,
    height: 2,
    width: 2,
  },


  wooden_shield: {
    itemId: 'wooden_shield',
    name: 'Wooden Shield',
    image: 'wooden-shield',
    type: 'offHand',
    level: 1,
    armor: 10,
    power: 3,
    probability: 30,
    sellPrice: 30,
    buyPrice: 75,
  },
  plate_helmet: {
    itemId: 'plate_helmet',
    name: 'Plate Helmet',
    image: 'plate-helmet',
    type: 'head',
    level: 1,
    armor: 5,
    power: 3,
    probability: 20,
    sellPrice: 30,
    buyPrice: 75,
  },
  choker_of_shielding: {
    itemId: 'choker_of_shielding',
    name: 'Choker of Shielding',
    image: 'choker-of-shielding',
    type: 'necklace',
    level: 1,
    armor: 5,
    endurance: 5,
    power: 5,
    probability: 10,
    sellPrice: 50,
    buyPrice: 100,
  },
  heart_of_primal_winter: {
    itemId: 'heart_of_primal_winter',
    name: 'Heat of Primal Winter',
    image: 'heart-of-primal-winter',
    type: 'necklace',
    level: 1,
    strength: 5,
    dexterity: 3,
    power: 5,
    probability: 10,
    sellPrice: 50,
    buyPrice: 100,
  },
  ocher_ring: {
    itemId: 'ocher_ring',
    name: 'Ocher Ring',
    image: 'ocher-ring',
    type: 'ring',
    level: 1,
    strength: 2,
    intelligence: 3,
    power: 5,
    probability: 15,
    sellPrice: 50,
    buyPrice: 100,
  },
  iron_chest: {
    itemId: 'iron_chest',
    name: 'Iron Chest',
    image: 'iron-chest',
    type: 'chest',
    level: 1,
    armor: 10,
    power: 3,
    probability: 15,
    sellPrice: 50,
    buyPrice: 100,
  },
  chainmail_leggings: {
    itemId: ' chainmail_leggings',
    name: 'Chainmail Leggings',
    image: ' chainmail-leggings',
    type: 'legs',
    level: 1,
    armor: 5,
    power: 3,
    probability: 20,
    sellPrice: 30,
    buyPrice: 75,
  },
  reinforced_boots: {
    itemId: 'reinforced_boots',
    name: 'Reinforced Boots',
    image: 'reinforced-boots',
    type: 'boots',
    level: 1,
    armor: 5,
    power: 3,
    probability: 20,
    sellPrice: 30,
    buyPrice: 75,
  },
  runic_sword: {
    itemId: 'runic_swords',
    name: 'Runic Sword',
    image: 'runic-sword',
    type: 'mainHand',
    level: 2,
    damage: [5, 7],
    power: 6,
    probability: 10,
    sellPrice: 210,
    buyPrice: 380,
  },
  rock_of_aegis: {
    itemId: 'rock_of_aegis',
    name: 'Rock of Aegis',
    image: 'rock-of-aegis',
    type: 'offHand',
    level: 1,
    armor: 25,
    power: 8,
    probability: 5,
    sellPrice: 260,
    buyPrice: 400,
  },
  vanguard_breastplate: {
    itemId: 'vanguard_breastplate',
    name: 'Vanguard Breastplate',
    image: 'vanguard-breastplate',
    type: 'chest',
    level: 2,
    armor: 20,
    power: 6,
    probability: 10,
    sellPrice: 210,
    buyPrice: 380,
  },
};