export interface ItemInterface {
  _id: string,
  id: string,
  name: string,
  image: string,
  type?: 'head' | 'chest' | 'gloves' | 'cloak' | 'legs' | 'boots' | 'mainHand' | 'offHand' | 'necklace' | 'ring',
  damage?: number[],
  armor?: number,
  strength?: number,
  endurance?: number,
  agility?: number,
  dexterity?: number,
  charisma?: number,
  intelligence?: number,
  power: number,
  probability: number,
  level: number,
  width: number,
  height: number,
}
